name: 'Auto Reviewers'
description: 'Recognize and assign reviewers and codeowners'
inputs:
  source:
    description: 'Filename which contain owners metadata to look for'
    required: true
  ignore:
    description: 'Files to be ignored when assigning reviewers'
    required: false
  token:
    description: 'GitHub token'
    required: true
  labels:
    description: 'Record, with `label` keys and glob path values.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: target
  color: gray-dark
